from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.parser import read_events, summarize_events, calculate_severity


app = FastAPI(
    title="BaitTrace API",
    description="Cybersecurity Honeypot Monitoring API",
    version="1.0.0",
)


# =========================================================
# CORS
# =========================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# =========================================================
# HOME
# =========================================================

@app.get("/")
def home():
    return {
        "name": "BaitTrace",
        "status": "online",
        "message": "BaitTrace Honeypot API is running",
    }


# =========================================================
# STATS
# =========================================================

@app.get("/api/stats")
def get_stats():

    events = read_events()

    summary = summarize_events(events)

    return summary


# =========================================================
# RISK CALCULATION
# =========================================================

def calculate_attacker_risk(events):
    """
    Calculate the risk score for one attacker
    based on the events generated by Cowrie.
    """

    score = 0

    for event in events:

        event_id = event.get("eventid", "")

        # Failed login attempt
        if event_id == "cowrie.login.failed":
            score += 10

        # Successful login
        elif event_id == "cowrie.login.success":
            score += 30

        # Command executed
        elif event_id == "cowrie.command.input":

            # Base command score
            score += 15

            # Extra weight for dangerous commands
            command = (event.get("input") or "").lower()

            critical_commands = [
                "rm -rf",
                "mkfs",
                "dd if=",
                "shutdown",
                "reboot",
            ]

            high_commands = [
                "wget",
                "curl",
                "chmod +x",
                "nc ",
                "netcat",
                "bash -i",
                "python -c",
                "perl -e",
            ]

            if any(item in command for item in critical_commands):
                score += 30

            elif any(item in command for item in high_commands):
                score += 20

        # Failed command
        elif event_id == "cowrie.command.failed":
            score += 5

        # New SSH session
        elif event_id == "cowrie.session.connect":
            score += 2

    # -----------------------------------------------------
    # Risk level
    # -----------------------------------------------------

    if score >= 70:
        risk_level = "CRITICAL"

    elif score >= 40:
        risk_level = "HIGH"

    elif score >= 20:
        risk_level = "MEDIUM"

    else:
        risk_level = "LOW"

    return score, risk_level


# =========================================================
# ATTACKERS
# =========================================================

@app.get("/api/attackers")
def get_attackers():

    events = read_events()

    attackers = {}

    for event in events:

        ip = event.get("src_ip")

        if not ip:
            continue

        # -------------------------------------------------
        # Create attacker
        # -------------------------------------------------

        if ip not in attackers:

            attackers[ip] = {
                "ip": ip,
                "events": 0,
                "logins": 0,
                "successful_logins": 0,
                "commands": 0,
                "failed_commands": 0,
                "first_seen": event.get("timestamp"),
                "last_seen": event.get("timestamp"),
            }

        attacker = attackers[ip]

        # -------------------------------------------------
        # Event count
        # -------------------------------------------------

        attacker["events"] += 1

        # -------------------------------------------------
        # Timestamp
        # -------------------------------------------------

        timestamp = event.get("timestamp")

        if timestamp:

            if not attacker["first_seen"]:
                attacker["first_seen"] = timestamp

            attacker["last_seen"] = timestamp

        # -------------------------------------------------
        # Event type
        # -------------------------------------------------

        event_id = event.get("eventid", "")

        # Failed login
        if event_id == "cowrie.login.failed":

            attacker["logins"] += 1

        # Successful login
        elif event_id == "cowrie.login.success":

            attacker["successful_logins"] += 1

        # Command executed
        elif event_id == "cowrie.command.input":

            attacker["commands"] += 1

        # Failed command
        elif event_id == "cowrie.command.failed":

            attacker["failed_commands"] += 1

    # =====================================================
    # CALCULATE REAL RISK FOR EVERY ATTACKER
    # =====================================================

    attacker_list = []

    for ip, attacker in attackers.items():

        attacker_events = [
            event
            for event in events
            if event.get("src_ip") == ip
        ]

        risk_score, risk_level = calculate_attacker_risk(
            attacker_events
        )

        attacker["risk_score"] = risk_score
        attacker["risk_level"] = risk_level

        attacker_list.append(attacker)

    # Highest risk first
    attacker_list.sort(
        key=lambda attacker: attacker["risk_score"],
        reverse=True,
    )

    return attacker_list


# =========================================================
# EVENTS
# =========================================================

@app.get("/api/events")
def get_events():

    events = read_events()

    formatted_events = []

    for event in events:

        event_copy = dict(event)

        # Make sure severity always comes from backend
        event_copy["severity"] = calculate_severity(event)

        formatted_events.append(event_copy)

    # Newest events first
    formatted_events.reverse()

    return formatted_events


# =========================================================
# COMMANDS
# =========================================================

@app.get("/api/commands")
def get_commands():

    events = read_events()

    commands = []

    for event in events:

        event_id = event.get("eventid", "")

        if event_id == "cowrie.command.input":

            commands.append(
                {
                    "timestamp": event.get("timestamp"),
                    "ip": event.get("src_ip"),
                    "session": event.get("session"),
                    "command": event.get("input", ""),
                    "severity": calculate_severity(event),
                }
            )

    return list(reversed(commands))


# =========================================================
# LOGIN ATTEMPTS
# =========================================================

@app.get("/api/logins")
def get_logins():

    events = read_events()

    logins = []

    for event in events:

        event_id = event.get("eventid", "")

        if event_id in [
            "cowrie.login.failed",
            "cowrie.login.success",
        ]:

            logins.append(
                {
                    "timestamp": event.get("timestamp"),
                    "ip": event.get("src_ip"),
                    "username": event.get("username"),
                    "password": event.get("password"),
                    "success": event_id
                    == "cowrie.login.success",
                    "severity": calculate_severity(event),
                }
            )

    return list(reversed(logins))


# =========================================================
# ATTACKER RISK
# =========================================================

@app.get("/api/attackers/{ip}/risk")
def get_attacker_risk(ip: str):

    events = read_events()

    attacker_events = [
        event
        for event in events
        if event.get("src_ip") == ip
    ]

    score, risk_level = calculate_attacker_risk(
        attacker_events
    )

    return {
        "ip": ip,
        "risk_score": score,
        "risk_level": risk_level,
        "events": len(attacker_events),
    }


# =========================================================
# SERVER STATUS
# =========================================================

@app.get("/api/status")
def get_status():

    events = read_events()

    return {
        "system": "BaitTrace",
        "status": "online",
        "total_events": len(events),
        "honeypot": "Cowrie",
        "api": "FastAPI",
    }